### ISSUE TITLE
How to prepare input files?

### ISSUE THREAD

**Issue by Sonia-Bedi** [TheJacksonLaboratory/CUP-AI-Dx#3]
Hi,
Please pardon me if my question turn out to be naiive, as I am new to it. 
I want to know how do I prepare my input file? I did check the "ExternalDataMeta.csv" file format. How can I achieve that for my samples. Is there a recommended tool? My data is the output from the NGS workflow.

Sonia

**Comment by yuz12012** [comment]
Hi Sonia, the expression is log(TPM+1). I would recommend using the same data processing settings as the TCGA RNA-seq data set.

**Comment by Sonia-Bedi** [comment]
Hi @yuz12012, could you please share a link to above?

**Comment by yuz12012** [comment]
> Hi @yuz12012, could you please share a link to above?

Sure, https://docs.gdc.cancer.gov/Data/Bioinformatics_Pipelines/Expression_mRNA_Pipeline/
