### ISSUE TITLE
Solving environment: failed

### ISSUE THREAD

**Issue by Souzavgp** [TheJacksonLaboratory/CUP-AI-Dx#4]
I have these errors message

ResolvePackageNotFound: 
  - openmp_impl==4.5=0_gnu
  - gxx_impl_linux-64==7.3.0=hdf63c60_2
  - libgcc-ng==9.2.0=h24d8f2e_1
  - gcc_impl_linux-64==7.3.0=habb00fd_2
  - 
Could you help me how solve them?

My system
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04

**Comment by yuz12012** [comment]
Thanks for the interest in our tools. It seems the problem is caused by some system specific dependency. We specifically build a docker container to solve these kinds of problems. For more details, please refer to the bottom section of
Readme page.
